apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mylmsacr.azurecr.io/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: FRONTEND_URL
          value: "http://frontend-service"
        - name: DB_HOST
          value: "your-mysql-host" # Update with your MySQL host
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "" # Use a secret in production
        - name: DB_NAME
          value: "gymdb"
        - name: CLOUDINARY_CLOUD_NAME
          value: "your_cloud_name"
        - name: CLOUDINARY_API_KEY
          value: "your_api_key"
        - name: CLOUDINARY_API_SECRET
          value: "your_api_secret"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP