apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: acr-secret   # 🔑 UN SEUL imagePullSecret ici
      containers:
      - name: frontend
        image: mylmsacr.azurecr.io/frontend:placeholder # sera remplacé par le pipeline
        ports:
        - containerPort: 5173
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: VITE_API_BASE_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_API_BASE_URL
        - name: VITE_API_TIMEOUT
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_API_TIMEOUT
        - name: VITE_APP_ENV
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_APP_ENV
        - name: VITE_APP_VERSION
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_APP_VERSION
        - name: VITE_FEATURE_PAYMENTS_ENABLED
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_FEATURE_PAYMENTS_ENABLED
        - name: VITE_FEATURE_REPORTS_ENABLED
          valueFrom:
            secretKeyRef:
              name: frontend-secrets
              key: VITE_FEATURE_REPORTS_ENABLED